!======================================================================
! The following lines have been generated by a python script: input_variables.py 
! Do not alter them directly: they will be overriden sooner or later by the script
! To add a new input variable, modify the script directly
! Generated by input_parameter.py on 04 July 2016
!======================================================================

write(stdout,'(x,a24,6x,a)') 'scf',scf 
write(stdout,'(x,a24,6x,a)') 'postscf',postscf 
write(stdout,'(x,a24,2x,es16.8)') 'alpha_hybrid',alpha_hybrid 
write(stdout,'(x,a24,2x,es16.8)') 'beta_hybrid',beta_hybrid 
write(stdout,'(x,a24,2x,es16.8)') 'gamma_hybrid',gamma_hybrid 
write(stdout,'(x,a24,6x,a)') 'basis',basis 
write(stdout,'(x,a24,6x,a)') 'auxil_basis',auxil_basis 
write(stdout,'(x,a24,6x,a)') 'basis_path',basis_path 
write(stdout,'(x,a24,6x,a)') 'gaussian_type',gaussian_type 
write(stdout,'(x,a24,6x,a)') 'no_4center',no_4center 
write(stdout,'(x,a24,2x,i8)') 'nspin',nspin 
write(stdout,'(x,a24,2x,es16.8)') 'charge',charge 
write(stdout,'(x,a24,2x,es16.8)') 'magnetization',magnetization 
write(stdout,'(x,a24,2x,es16.8)') 'temperature',temperature 
write(stdout,'(x,a24,6x,a)') 'grid_quality',grid_quality 
write(stdout,'(x,a24,6x,a)') 'integral_quality',integral_quality 
write(stdout,'(x,a24,6x,a)') 'partition_scheme',partition_scheme 
write(stdout,'(x,a24,2x,i8)') 'nscf',nscf 
write(stdout,'(x,a24,2x,es16.8)') 'alpha_mixing',alpha_mixing 
write(stdout,'(x,a24,6x,a)') 'mixing_scheme',mixing_scheme 
write(stdout,'(x,a24,2x,es16.8)') 'level_shifting_energy',level_shifting_energy 
write(stdout,'(x,a24,2x,es16.8)') 'tolscf',tolscf 
write(stdout,'(x,a24,2x,i8)') 'mixing_first_nscf',mixing_first_nscf 
write(stdout,'(x,a24,2x,es16.8)') 'min_overlap',min_overlap 
write(stdout,'(x,a24,2x,i8)') 'npulay_hist',npulay_hist 
write(stdout,'(x,a24,6x,a)') 'tda',tda 
write(stdout,'(x,a24,6x,a)') 'triplet',triplet 
write(stdout,'(x,a24,2x,i8)') 'nexcitation',nexcitation 
write(stdout,'(x,a24,2x,es16.8)') 'toldav',toldav 
write(stdout,'(x,a24,6x,a)') 'frozencore',frozencore 
write(stdout,'(x,a24,2x,i8)') 'ncoreg',ncoreg 
write(stdout,'(x,a24,2x,i8)') 'ncorew',ncorew 
write(stdout,'(x,a24,2x,i8)') 'nvirtualg',nvirtualg 
write(stdout,'(x,a24,2x,i8)') 'nvirtualw',nvirtualw 
write(stdout,'(x,a24,2x,i8)') 'nvirtualspa',nvirtualspa 
write(stdout,'(x,a24,2x,i8)') 'selfenergy_state_min',selfenergy_state_min 
write(stdout,'(x,a24,2x,i8)') 'selfenergy_state_max',selfenergy_state_max 
write(stdout,'(x,a24,2x,i8)') 'selfenergy_state_range',selfenergy_state_range 
write(stdout,'(x,a24,2x,i8)') 'nomega_sigma',nomega_sigma 
write(stdout,'(x,a24,2x,es16.8)') 'step_sigma',step_sigma 
write(stdout,'(x,a24,6x,a)') 'ignore_restart',ignore_restart 
write(stdout,'(x,a24,6x,a)') 'ignore_bigrestart',ignore_bigrestart 
write(stdout,'(x,a24,6x,a)') 'print_matrix',print_matrix 
write(stdout,'(x,a24,6x,a)') 'print_eri',print_eri 
write(stdout,'(x,a24,6x,a)') 'print_wfn',print_wfn 
write(stdout,'(x,a24,6x,a)') 'print_cube',print_cube 
write(stdout,'(x,a24,6x,a)') 'print_w',print_w 
write(stdout,'(x,a24,6x,a)') 'print_restart',print_restart 
write(stdout,'(x,a24,6x,a)') 'print_bigrestart',print_bigrestart 
write(stdout,'(x,a24,6x,a)') 'print_sigma',print_sigma 
write(stdout,'(x,a24,6x,a)') 'print_pdos',print_pdos 
write(stdout,'(x,a24,6x,a)') 'length_unit',length_unit 
write(stdout,'(x,a24,2x,i8)') 'natom',natom 
write(stdout,'(x,a24,6x,a)') 'xyz_file',xyz_file 
write(stdout,'(x,a24,2x,i8)') 'nghost',nghost 
write(stdout,'(x,a24,2x,es16.8)') 'eta',eta 
write(stdout,'(x,a24,2x,es16.8)') 'scissor',scissor 
write(stdout,'(x,a24,2x,i8)') 'scalapack_block_min',scalapack_block_min 
write(stdout,'(x,a24,2x,i8)') 'scalapack_nprow',scalapack_nprow 
write(stdout,'(x,a24,2x,i8)') 'scalapack_npcol',scalapack_npcol 
write(stdout,'(x,a24,2x,es16.8)') 'alpha_cohsex',alpha_cohsex 
write(stdout,'(x,a24,2x,es16.8)') 'beta_cohsex',beta_cohsex 
write(stdout,'(x,a24,2x,i8)') 'dft_core',dft_core 
write(stdout,'(x,a24,2x,es16.8)') 'gamma_cohsex',gamma_cohsex 
write(stdout,'(x,a24,2x,es16.8)') 'delta_cohsex',delta_cohsex 
write(stdout,'(x,a24,2x,es16.8)') 'epsilon_cohsex',epsilon_cohsex 
write(stdout,'(x,a24,6x,a)') 'virtual_fno',virtual_fno 
write(stdout,'(x,a24,2x,es16.8)') 'rcut_mbpt',rcut_mbpt 


!======================================================================
