!======================================================================
! The following lines have been generated by python script: input_variables.py 
! Do not alter them directly: they will be overriden sooner or later by the script
! To add a new input variable, modify the script directly
! Generated by input_parameter.py on 20 May 2015
!======================================================================

 namelist /molgw/   &
    scf,       &
    postscf,       &
    alpha_hybrid,       &
    beta_hybrid,       &
    gamma_hybrid,       &
    basis,       &
    auxil_basis,       &
    basis_path,       &
    gaussian_type,       &
    no_4center,       &
    nspin,       &
    charge,       &
    magnetization,       &
    grid_quality,       &
    integral_quality,       &
    nscf,       &
    alpha_mixing,       &
    mixing_scheme,       &
    tolscf,       &
    tda,       &
    triplet,       &
    frozencore,       &
    ncoreg,       &
    ncorew,       &
    nvirtualg,       &
    nvirtualw,       &
    nomega_sigma,       &
    step_sigma,       &
    ignore_restart,       &
    ignore_bigrestart,       &
    print_matrix,       &
    print_eri,       &
    print_wfn,       &
    print_w,       &
    print_restart,       &
    print_sigma,       &
    length_unit,       &
    natom,       &
    nghost,       &
    eta

!=====

 scf=''
 postscf=''
 alpha_hybrid=0.0
 beta_hybrid=0.0
 gamma_hybrid=1000000.0
 basis=''
 auxil_basis=''
 basis_path='./'
 gaussian_type='pure'
 no_4center='no'
 nspin=1
 charge=0.0
 magnetization=0.0
 grid_quality='high'
 integral_quality='high'
 nscf=30
 alpha_mixing=0.7
 mixing_scheme='pulay'
 tolscf=1e-07
 tda='no'
 triplet='no'
 frozencore='no'
 ncoreg=0
 ncorew=0
 nvirtualg=100000
 nvirtualw=100000
 nomega_sigma=51
 step_sigma=0.01
 ignore_restart='no'
 ignore_bigrestart='no'
 print_matrix='no'
 print_eri='no'
 print_wfn='no'
 print_w='no'
 print_restart='yes'
 print_sigma='no'
 length_unit='angstrom'
 natom=0
 nghost=0
 eta=0.001


!======================================================================
