!======================================================================
! This file is part of MOLGW.
! The following lines have been generated by python script: prepare_sourcecode.py 
! Do not alter them directly: they will be overriden sooner or later by the script
! To add a new input variable, modify the script directly
! Generated by prepare_sourcecode.py
!======================================================================

<<<<<<< HEAD
 default_basis_path = '/home/maliyov/github/molgw-master/basis/' 
=======
 default_basis_path = '/home/maliyov/github/molgw-read-restart/basis/' 
>>>>>>> 0bb58566ff63fe2778b41de3fde237e88cbd784e

