!======================================================================
! This file is part of MOLGW.
! The following lines have been generated by python script: prepare_sourcecode.py 
! Do not alter them directly: they will be overriden sooner or later by the script
! To add a new input variable, modify the script directly
! Generated by prepare_sourcecode.py
!======================================================================

<<<<<<< HEAD
 default_basis_path = '/home/maliyov/github/molgw-tddft/basis/' 
=======
 default_basis_path = '/home/bruneval/devel/molgw-devel-fullci/basis/' 
>>>>>>> 4556b1a9af5305daa43d2f86c02f2732e18addf3

