!======================================================================
! The following lines have been generated by a python script: input_variables.py 
! Do not alter them directly: they will be overriden sooner or later by the script
! To add a new input variable, modify the script directly
! Generated by input_parameter.py on 27 March 2018
!======================================================================

 write(stdout,'(1x,a24,6x,a)') 'scf',scf 
 write(stdout,'(1x,a24,6x,a)') 'postscf',postscf 
 write(stdout,'(1x,a24,6x,a)') 'move_nuclei',move_nuclei 
 write(stdout,'(1x,a24,2x,i8)') 'nstep',nstep 
 write(stdout,'(1x,a24,2x,es16.8)') 'tolforce',tolforce 
 write(stdout,'(1x,a24,2x,es16.8)') 'alpha_hybrid',alpha_hybrid 
 write(stdout,'(1x,a24,2x,es16.8)') 'beta_hybrid',beta_hybrid 
 write(stdout,'(1x,a24,2x,es16.8)') 'gamma_hybrid',gamma_hybrid 
 write(stdout,'(1x,a24,6x,a)') 'basis',basis 
 write(stdout,'(1x,a24,6x,a)') 'auxil_basis',auxil_basis 
 write(stdout,'(1x,a24,6x,a)') 'basis_path',basis_path 
 write(stdout,'(1x,a24,6x,a)') 'small_basis',small_basis 
 write(stdout,'(1x,a24,6x,a)') 'ecp_small_basis',ecp_small_basis 
 write(stdout,'(1x,a24,6x,a)') 'gaussian_type',gaussian_type 
 write(stdout,'(1x,a24,2x,i8)') 'nspin',nspin 
 write(stdout,'(1x,a24,2x,es16.8)') 'charge',charge 
 write(stdout,'(1x,a24,2x,es16.8)') 'magnetization',magnetization 
 write(stdout,'(1x,a24,2x,es16.8)') 'temperature',temperature 
 write(stdout,'(1x,a24,6x,a)') 'grid_quality',grid_quality 
 write(stdout,'(1x,a24,6x,a)') 'tddft_grid_quality',tddft_grid_quality 
 write(stdout,'(1x,a24,6x,a)') 'integral_quality',integral_quality 
 write(stdout,'(1x,a24,6x,a)') 'partition_scheme',partition_scheme 
 write(stdout,'(1x,a24,2x,i8)') 'nscf',nscf 
 write(stdout,'(1x,a24,2x,es16.8)') 'alpha_mixing',alpha_mixing 
 write(stdout,'(1x,a24,6x,a)') 'mixing_scheme',mixing_scheme 
 write(stdout,'(1x,a24,2x,es16.8)') 'diis_switch',diis_switch 
 write(stdout,'(1x,a24,2x,es16.8)') 'level_shifting_energy',level_shifting_energy 
 write(stdout,'(1x,a24,6x,a)') 'init_hamiltonian',init_hamiltonian 
 write(stdout,'(1x,a24,2x,es16.8)') 'tolscf',tolscf 
 write(stdout,'(1x,a24,2x,es16.8)') 'min_overlap',min_overlap 
 write(stdout,'(1x,a24,2x,i8)') 'npulay_hist',npulay_hist 
 write(stdout,'(1x,a24,2x,i8)') 'nstep_gw',nstep_gw 
 write(stdout,'(1x,a24,6x,a)') 'tda',tda 
 write(stdout,'(1x,a24,6x,a)') 'triplet',triplet 
 write(stdout,'(1x,a24,2x,i8)') 'nexcitation',nexcitation 
 write(stdout,'(1x,a24,2x,es16.8)') 'toldav',toldav 
 write(stdout,'(1x,a24,2x,i8)') 'nstep_dav',nstep_dav 
 write(stdout,'(1x,a24,6x,a)') 'frozencore',frozencore 
 write(stdout,'(1x,a24,2x,i8)') 'ncoreg',ncoreg 
 write(stdout,'(1x,a24,2x,i8)') 'ncorew',ncorew 
 write(stdout,'(1x,a24,2x,i8)') 'nvirtualg',nvirtualg 
 write(stdout,'(1x,a24,2x,i8)') 'nvirtualw',nvirtualw 
 write(stdout,'(1x,a24,2x,i8)') 'nvirtualspa',nvirtualspa 
 write(stdout,'(1x,a24,2x,i8)') 'nomega_imag',nomega_imag 
 write(stdout,'(1x,a24,2x,i8)') 'selfenergy_state_min',selfenergy_state_min 
 write(stdout,'(1x,a24,2x,i8)') 'selfenergy_state_max',selfenergy_state_max 
 write(stdout,'(1x,a24,2x,i8)') 'selfenergy_state_range',selfenergy_state_range 
 write(stdout,'(1x,a24,2x,i8)') 'nomega_sigma',nomega_sigma 
 write(stdout,'(1x,a24,2x,es16.8)') 'step_sigma',step_sigma 
 write(stdout,'(1x,a24,6x,a)') 'pt3_a_diagrams',pt3_a_diagrams 
 write(stdout,'(1x,a24,6x,a)') 'read_restart',read_restart 
 write(stdout,'(1x,a24,6x,a)') 'ignore_bigrestart',ignore_bigrestart 
 write(stdout,'(1x,a24,6x,a)') 'force_energy_qp',force_energy_qp 
 write(stdout,'(1x,a24,6x,a)') 'print_hartree',print_hartree 
 write(stdout,'(1x,a24,6x,a)') 'print_exchange',print_exchange 
 write(stdout,'(1x,a24,6x,a)') 'print_eri',print_eri 
 write(stdout,'(1x,a24,6x,a)') 'print_wfn',print_wfn 
 write(stdout,'(1x,a24,6x,a)') 'print_cube',print_cube 
 write(stdout,'(1x,a24,6x,a)') 'read_fchk',read_fchk 
 write(stdout,'(1x,a24,6x,a)') 'print_w',print_w 
 write(stdout,'(1x,a24,6x,a)') 'print_restart',print_restart 
 write(stdout,'(1x,a24,6x,a)') 'print_bigrestart',print_bigrestart 
 write(stdout,'(1x,a24,6x,a)') 'print_sigma',print_sigma 
 write(stdout,'(1x,a24,6x,a)') 'print_pdos',print_pdos 
 write(stdout,'(1x,a24,6x,a)') 'print_multipole',print_multipole 
 write(stdout,'(1x,a24,6x,a)') 'length_unit',length_unit 
 write(stdout,'(1x,a24,2x,i8)') 'natom',natom 
 write(stdout,'(1x,a24,6x,a)') 'xyz_file',xyz_file 
 write(stdout,'(1x,a24,2x,i8)') 'nghost',nghost 
 write(stdout,'(1x,a24,2x,es16.8)') 'eta',eta 
 write(stdout,'(1x,a24,2x,es16.8)') 'scissor',scissor 
 write(stdout,'(1x,a24,2x,es16.8)') 'grid_memory',grid_memory 
 write(stdout,'(1x,a24,2x,i8)') 'scalapack_block_min',scalapack_block_min 
 write(stdout,'(1x,a24,2x,i8)') 'scalapack_nprow',scalapack_nprow 
 write(stdout,'(1x,a24,2x,i8)') 'scalapack_npcol',scalapack_npcol 
 write(stdout,'(1x,a24,2x,i8)') 'mpi_nproc_ortho',mpi_nproc_ortho 
 write(stdout,'(1x,a24,2x,es16.8)') 'alpha_cohsex',alpha_cohsex 
 write(stdout,'(1x,a24,2x,es16.8)') 'beta_cohsex',beta_cohsex 
 write(stdout,'(1x,a24,2x,i8)') 'dft_core',dft_core 
 write(stdout,'(1x,a24,2x,es16.8)') 'gamma_cohsex',gamma_cohsex 
 write(stdout,'(1x,a24,2x,es16.8)') 'delta_cohsex',delta_cohsex 
 write(stdout,'(1x,a24,2x,es16.8)') 'epsilon_cohsex',epsilon_cohsex 
 write(stdout,'(1x,a24,6x,a)') 'virtual_fno',virtual_fno 
 write(stdout,'(1x,a24,2x,es16.8)') 'rcut_mbpt',rcut_mbpt 
 write(stdout,'(1x,a24,6x,a)') 'gwgamma_tddft',gwgamma_tddft 
 write(stdout,'(1x,a24,6x,a)') 'ecp_type',ecp_type 
 write(stdout,'(1x,a24,6x,a)') 'ecp_elements',ecp_elements 
 write(stdout,'(1x,a24,6x,a)') 'ecp_quality',ecp_quality 
 write(stdout,'(1x,a24,6x,a)') 'ecp_basis',ecp_basis 
 write(stdout,'(1x,a24,6x,a)') 'ecp_auxil_basis',ecp_auxil_basis 
 write(stdout,'(1x,a24,6x,a)') 'ci_greens_function',ci_greens_function 
 write(stdout,'(1x,a24,6x,a)') 'ci_type',ci_type 
 write(stdout,'(1x,a24,2x,i8)') 'ci_nstate',ci_nstate 
 write(stdout,'(1x,a24,2x,i8)') 'ci_nstate_self',ci_nstate_self 
 write(stdout,'(1x,a24,2x,i8)') 'ci_spin_multiplicity',ci_spin_multiplicity 


!======================================================================
