!======================================================================
! The following lines have been generated by a python script: input_variables.py 
! Do not alter them directly: they will be overriden sooner or later by the script
! To add a new input variable, modify the script directly
! Generated by input_parameter.py on 16 February 2017
!======================================================================

 write(stdout,'(1x,a24,6x,a)') 'scf',scf 
 write(stdout,'(1x,a24,6x,a)') 'postscf',postscf 
 write(stdout,'(1x,a24,2x,es16.8)') 'alpha_hybrid',alpha_hybrid 
 write(stdout,'(1x,a24,2x,es16.8)') 'beta_hybrid',beta_hybrid 
 write(stdout,'(1x,a24,2x,es16.8)') 'gamma_hybrid',gamma_hybrid 
 write(stdout,'(1x,a24,6x,a)') 'basis',basis 
 write(stdout,'(1x,a24,6x,a)') 'auxil_basis',auxil_basis 
 write(stdout,'(1x,a24,6x,a)') 'basis_path',basis_path 
 write(stdout,'(1x,a24,6x,a)') 'small_basis',small_basis 
 write(stdout,'(1x,a24,6x,a)') 'ecp_small_basis',ecp_small_basis 
 write(stdout,'(1x,a24,6x,a)') 'gaussian_type',gaussian_type 
 write(stdout,'(1x,a24,6x,a)') 'no_4center',no_4center 
 write(stdout,'(1x,a24,2x,i8)') 'nspin',nspin 
 write(stdout,'(1x,a24,2x,es16.8)') 'charge',charge 
 write(stdout,'(1x,a24,2x,es16.8)') 'magnetization',magnetization 
 write(stdout,'(1x,a24,2x,es16.8)') 'temperature',temperature 
 write(stdout,'(1x,a24,6x,a)') 'grid_quality',grid_quality 
 write(stdout,'(1x,a24,6x,a)') 'tddft_grid_quality',tddft_grid_quality 
 write(stdout,'(1x,a24,6x,a)') 'integral_quality',integral_quality 
 write(stdout,'(1x,a24,6x,a)') 'partition_scheme',partition_scheme 
 write(stdout,'(1x,a24,2x,i8)') 'nscf',nscf 
 write(stdout,'(1x,a24,2x,es16.8)') 'alpha_mixing',alpha_mixing 
 write(stdout,'(1x,a24,6x,a)') 'mixing_scheme',mixing_scheme 
 write(stdout,'(1x,a24,2x,es16.8)') 'diis_switch',diis_switch 
 write(stdout,'(1x,a24,2x,es16.8)') 'level_shifting_energy',level_shifting_energy 
 write(stdout,'(1x,a24,6x,a)') 'init_hamiltonian',init_hamiltonian 
 write(stdout,'(1x,a24,2x,es16.8)') 'tolscf',tolscf 
 write(stdout,'(1x,a24,2x,es16.8)') 'min_overlap',min_overlap 
 write(stdout,'(1x,a24,2x,i8)') 'npulay_hist',npulay_hist 
 write(stdout,'(1x,a24,6x,a)') 'tda',tda 
 write(stdout,'(1x,a24,6x,a)') 'triplet',triplet 
 write(stdout,'(1x,a24,2x,i8)') 'nexcitation',nexcitation 
 write(stdout,'(1x,a24,2x,es16.8)') 'toldav',toldav 
 write(stdout,'(1x,a24,6x,a)') 'frozencore',frozencore 
 write(stdout,'(1x,a24,2x,i8)') 'ncoreg',ncoreg 
 write(stdout,'(1x,a24,2x,i8)') 'ncorew',ncorew 
 write(stdout,'(1x,a24,2x,i8)') 'nvirtualg',nvirtualg 
 write(stdout,'(1x,a24,2x,i8)') 'nvirtualw',nvirtualw 
 write(stdout,'(1x,a24,2x,i8)') 'nvirtualspa',nvirtualspa 
 write(stdout,'(1x,a24,2x,i8)') 'selfenergy_state_min',selfenergy_state_min 
 write(stdout,'(1x,a24,2x,i8)') 'selfenergy_state_max',selfenergy_state_max 
 write(stdout,'(1x,a24,2x,i8)') 'selfenergy_state_range',selfenergy_state_range 
 write(stdout,'(1x,a24,2x,i8)') 'nomega_sigma',nomega_sigma 
 write(stdout,'(1x,a24,2x,es16.8)') 'step_sigma',step_sigma 
 write(stdout,'(1x,a24,6x,a)') 'ignore_restart',ignore_restart 
 write(stdout,'(1x,a24,6x,a)') 'ignore_bigrestart',ignore_bigrestart 
 write(stdout,'(1x,a24,6x,a)') 'print_matrix',print_matrix 
 write(stdout,'(1x,a24,6x,a)') 'print_eri',print_eri 
 write(stdout,'(1x,a24,6x,a)') 'print_wfn',print_wfn 
 write(stdout,'(1x,a24,6x,a)') 'print_cube',print_cube 
 write(stdout,'(1x,a24,6x,a)') 'print_w',print_w 
 write(stdout,'(1x,a24,6x,a)') 'print_restart',print_restart 
 write(stdout,'(1x,a24,6x,a)') 'print_bigrestart',print_bigrestart 
 write(stdout,'(1x,a24,6x,a)') 'print_sigma',print_sigma 
 write(stdout,'(1x,a24,6x,a)') 'print_pdos',print_pdos 
 write(stdout,'(1x,a24,6x,a)') 'print_multipole',print_multipole 
 write(stdout,'(1x,a24,6x,a)') 'length_unit',length_unit 
 write(stdout,'(1x,a24,2x,i8)') 'natom',natom 
 write(stdout,'(1x,a24,6x,a)') 'xyz_file',xyz_file 
 write(stdout,'(1x,a24,2x,i8)') 'nghost',nghost 
 write(stdout,'(1x,a24,2x,es16.8)') 'eta',eta 
 write(stdout,'(1x,a24,2x,es16.8)') 'scissor',scissor 
 write(stdout,'(1x,a24,2x,i8)') 'scalapack_block_min',scalapack_block_min 
 write(stdout,'(1x,a24,2x,i8)') 'scalapack_nprow',scalapack_nprow 
 write(stdout,'(1x,a24,2x,i8)') 'scalapack_npcol',scalapack_npcol 
 write(stdout,'(1x,a24,2x,i8)') 'mpi_nproc_ortho',mpi_nproc_ortho 
 write(stdout,'(1x,a24,2x,es16.8)') 'alpha_cohsex',alpha_cohsex 
 write(stdout,'(1x,a24,2x,es16.8)') 'beta_cohsex',beta_cohsex 
 write(stdout,'(1x,a24,2x,i8)') 'dft_core',dft_core 
 write(stdout,'(1x,a24,2x,es16.8)') 'gamma_cohsex',gamma_cohsex 
 write(stdout,'(1x,a24,2x,es16.8)') 'delta_cohsex',delta_cohsex 
 write(stdout,'(1x,a24,2x,es16.8)') 'epsilon_cohsex',epsilon_cohsex 
 write(stdout,'(1x,a24,6x,a)') 'virtual_fno',virtual_fno 
 write(stdout,'(1x,a24,2x,es16.8)') 'rcut_mbpt',rcut_mbpt 
 write(stdout,'(1x,a24,6x,a)') 'gwgamma_tddft',gwgamma_tddft 
 write(stdout,'(1x,a24,6x,a)') 'ecp_type',ecp_type 
 write(stdout,'(1x,a24,6x,a)') 'ecp_elements',ecp_elements 
 write(stdout,'(1x,a24,6x,a)') 'ecp_quality',ecp_quality 
 write(stdout,'(1x,a24,6x,a)') 'ecp_basis',ecp_basis 
 write(stdout,'(1x,a24,6x,a)') 'ecp_auxil_basis',ecp_auxil_basis 
 write(stdout,'(1x,a24,2x,es16.8)') 'time_step',time_step 
 write(stdout,'(1x,a24,2x,es16.8)') 'time_sim',time_sim 
 write(stdout,'(1x,a24,6x,a)') 'prop_type',prop_type 
 write(stdout,'(1x,a24,6x,a)') 'excit_type',excit_type 
 write(stdout,'(1x,a24,2x,es16.8)') 'excit_kappa',excit_kappa 
 write(stdout,'(1x,a24,2x,es16.8)') 'excit_omega',excit_omega 
 write(stdout,'(1x,a24,2x,es16.8)') 'excit_time0',excit_time0 
 write(stdout,'(1x,a24,2x,"(",3(es16.8,2x),")")') 'excit_dir',excit_dir 
 write(stdout,'(1x,a24,6x,a)') 'print_tddft_matrices',print_tddft_matrices 
 write(stdout,'(1x,a24,6x,a)') 'print_cube_rho_tddft',print_cube_rho_tddft 
 write(stdout,'(1x,a24,6x,a)') 'calc_p_matrix_error',calc_p_matrix_error 
 write(stdout,'(1x,a24,6x,a)') 'error_prop_types',error_prop_types 
 write(stdout,'(1x,a24,6x,a)') 'error_time_steps',error_time_steps 
 write(stdout,'(1x,a24,2x,es16.8)') 'write_step',write_step 
 write(stdout,'(1x,a24,6x,a)') 'pred_corr',pred_corr 
 write(stdout,'(1x,a24,6x,a)') 'error_pred_corrs',error_pred_corrs 


!======================================================================
