!======================================================================
! This file is part of MOLGW.
! The following lines have been generated by python script: prepare_sourcecode.py 
! Do not alter them directly: they will be overriden sooner or later by the script
! To add a new input variable, modify the script directly
! Generated by prepare_sourcecode.py
!======================================================================

 git_sha = '9f6090d378274017615a5dda8a30472230d2fc48'

