!======================================================================
! This file is part of MOLGW.
! The following lines have been generated by python script: prepare_sourcecode.py 
! Do not alter them directly: they will be overriden sooner or later by the script
! To add a new input variable, modify the script directly
! Generated by prepare_sourcecode.py
!======================================================================

 git_sha = 'ee0b882e9d9251dafe4c600ba5ae54b26aa44d4f'

