!======================================================================
! This file is part of MOLGW.
! The following lines have been generated by python script: prepare_sourcecode.py 
! Do not alter them directly: they will be overriden sooner or later by the script
! To add a new input variable, modify the script directly
! Generated by prepare_sourcecode.py
!======================================================================

 git_sha = '06210ca5e91dfea30cb81b1061b55bb5e58bd6c3'

