!======================================================================
! The following lines have been generated by a python script: input_variables.py 
! Do not alter them directly: they will be overriden sooner or later by the script
! To add a new input variable, modify the script directly
! Generated by input_parameter.py on 29 July 2019
!======================================================================

 namelist /molgw/   &
    alpha_hybrid,       &
    alpha_mixing,       &
    auto_auxil_fsam,       &
    auto_auxil_lmaxinc,       &
    auxil_basis,       &
    basis,       &
    basis_path,       &
    beta_hybrid,       &
    calc_dens_disc,       &
    calc_q_matrix,       &
    calc_spectrum,       &
    charge,       &
    ci_greens_function,       &
    ci_nstate,       &
    ci_nstate_self,       &
    ci_spin_multiplicity,       &
    ci_type,       &
    density_matrix_damping,       &
    dft_core,       &
    diis_switch,       &
    ecp_auxil_basis,       &
    ecp_basis,       &
    ecp_elements,       &
    ecp_quality,       &
    ecp_small_basis,       &
    ecp_type,       &
    eri3_nbatch,       &
    eri3_npcol,       &
    eri3_nprow,       &
    eta,       &
    excit_dir,       &
    excit_kappa,       &
    excit_name,       &
    excit_omega,       &
    excit_time0,       &
    force_energy_qp,       &
    frozencore,       &
    gamma_hybrid,       &
    gaussian_type,       &
    grid_memory,       &
    grid_quality,       &
    gwgamma_tddft,       &
    ignore_bigrestart,       &
    incore,       &
    init_hamiltonian,       &
    integral_quality,       &
    kerker_k0,       &
    length_unit,       &
    level_shifting_energy,       &
    magnetization,       &
    memory_evaluation,       &
    min_overlap,       &
    mixing_scheme,       &
    move_nuclei,       &
    mpi_nproc_ortho,       &
    n_hist,       &
    n_iter,       &
    n_restart_tddft,       &
    natom,       &
    ncore_tddft,       &
    ncoreg,       &
    ncorew,       &
    nexcitation,       &
    nghost,       &
    nomega_imag,       &
    nomega_sigma,       &
    npulay_hist,       &
    nscf,       &
    nspin,       &
    nstep,       &
    nstep_dav,       &
    nstep_gw,       &
    nvirtualg,       &
    nvirtualw,       &
    partition_scheme,       &
    postscf,       &
    postscf_diago_flavor,       &
    pred_corr,       &
    print_bigrestart,       &
    print_cube,       &
    print_cube_diff_tddft,       &
    print_cube_rho_tddft,       &
    print_dens_traj,       &
    print_dens_traj_points_set,       &
    print_dens_traj_tddft,       &
    print_density_matrix,       &
    print_eri,       &
    print_hartree,       &
    print_line_rho_diff_tddft,       &
    print_line_rho_tddft,       &
    print_multipole,       &
    print_pdos,       &
    print_restart,       &
    print_rho_grid,       &
    print_sigma,       &
    print_tddft_matrices,       &
    print_tddft_restart,       &
    print_w,       &
    print_wfn,       &
    prop_type,       &
    pt3_a_diagrams,       &
    pt_density_matrix,       &
    r_disc,       &
    rcut_mbpt,       &
    read_fchk,       &
    read_restart,       &
    read_tddft_restart,       &
    scalapack_block_min,       &
    scf,       &
    scf_diago_flavor,       &
    scissor,       &
    selfenergy_state_max,       &
    selfenergy_state_min,       &
    selfenergy_state_range,       &
    small_basis,       &
    step_sigma,       &
    tda,       &
    tddft_frozencore,       &
    tddft_grid_quality,       &
    temperature,       &
    time_sim,       &
    time_step,       &
    toldav,       &
    tolforce,       &
    tolscf,       &
    triplet,       &
    use_correlated_density_matrix,       &
    vel_projectile,       &
    virtual_fno,       &
    write_step,       &
    xyz_file

!=====

 alpha_hybrid=0.0_dp 
 alpha_mixing=0.7_dp 
 auto_auxil_fsam=1.5_dp 
 auto_auxil_lmaxinc=1
 auxil_basis=''
 basis=''
 basis_path=''
 beta_hybrid=0.0_dp 
 calc_dens_disc='no'
 calc_q_matrix='no'
 calc_spectrum='no'
 charge=0.0_dp 
 ci_greens_function='holes'
 ci_nstate=1
 ci_nstate_self=1
 ci_spin_multiplicity=1
 ci_type='all'
 density_matrix_damping=0.0_dp 
 dft_core=0
 diis_switch=0.05_dp 
 ecp_auxil_basis=''
 ecp_basis=''
 ecp_elements=''
 ecp_quality='high'
 ecp_small_basis=''
 ecp_type=''
 eri3_nbatch=1
 eri3_npcol=1
 eri3_nprow=1
 eta=0.001_dp 
 excit_dir=(/ 1.0_dp , 0.0_dp , 0.0_dp /)
 excit_kappa=2e-05_dp 
 excit_name='NO'
 excit_omega=0.2_dp 
 excit_time0=3.0_dp 
 force_energy_qp='no'
 frozencore='no'
 gamma_hybrid=1000000.0_dp 
 gaussian_type='pure'
 grid_memory=400.0_dp 
 grid_quality='high'
 gwgamma_tddft='no'
 ignore_bigrestart='no'
 incore='yes'
 init_hamiltonian='guess'
 integral_quality='high'
 kerker_k0=0.0_dp 
 length_unit='angstrom'
 level_shifting_energy=0.0_dp 
 magnetization=0.0_dp 
 memory_evaluation='no'
 min_overlap=1e-05_dp 
 mixing_scheme='pulay'
 move_nuclei='no'
 mpi_nproc_ortho=1
 n_hist=2
 n_iter=2
 n_restart_tddft=50
 natom=0
 ncore_tddft=0
 ncoreg=0
 ncorew=0
 nexcitation=0
 nghost=0
 nomega_imag=0
 nomega_sigma=51
 npulay_hist=6
 nscf=50
 nspin=1
 nstep=50
 nstep_dav=15
 nstep_gw=1
 nvirtualg=100000
 nvirtualw=100000
 partition_scheme='ssf'
 postscf=''
 postscf_diago_flavor='R'
 pred_corr='PC1'
 print_bigrestart='yes'
 print_cube='no'
 print_cube_diff_tddft='no'
 print_cube_rho_tddft='no'
 print_dens_traj='no'
 print_dens_traj_points_set='no'
 print_dens_traj_tddft='no'
 print_density_matrix='no'
 print_eri='no'
 print_hartree='no'
 print_line_rho_diff_tddft='no'
 print_line_rho_tddft='no'
 print_multipole='no'
 print_pdos='no'
 print_restart='yes'
 print_rho_grid='no'
 print_sigma='no'
 print_tddft_matrices='no'
 print_tddft_restart='yes'
 print_w='no'
 print_wfn='no'
 prop_type='CN'
 pt3_a_diagrams='yes'
 pt_density_matrix='no'
 r_disc=200.0_dp 
 rcut_mbpt=1.0_dp 
 read_fchk='no'
 read_restart='no'
 read_tddft_restart='no'
 scalapack_block_min=1000
 scf=''
 scf_diago_flavor=' '
 scissor=0.0_dp 
 selfenergy_state_max=100000
 selfenergy_state_min=1
 selfenergy_state_range=100000
 small_basis=''
 step_sigma=0.01_dp 
 tda='no'
 tddft_frozencore='no'
 tddft_grid_quality='high'
 temperature=0.0_dp 
 time_sim=10.0_dp 
 time_step=1.0_dp 
 toldav=0.0001_dp 
 tolforce=1e-05_dp 
 tolscf=1e-07_dp 
 triplet='no'
 use_correlated_density_matrix='no'
 vel_projectile=(/ 0.0_dp , 0.0_dp , 1.0_dp /)
 virtual_fno='no'
 write_step=1_dp 
 xyz_file=''


!======================================================================
